#cloud-config
hostname: router1
fqdn: router1.local

# Configure network interfaces
write_files:
  - path: /etc/systemd/network/20-eth1.network
    content: |
      [Match]
      Name=eth1
      
      [Network]
      Address=10.0.1.1/24
  
  - path: /etc/systemd/network/30-eth2.network
    content: |
      [Match]
      Name=eth2
      
      [Network]
      Address=10.0.2.1/24

  - path: /etc/frr/frr.conf
    content: |
      hostname router1
      log file /var/log/frr/frr.log
      !
      router ospf
       network 10.0.0.0/8 area 0
      !
      line vty
      !

runcmd:
  - systemctl restart systemd-networkd
  - systemctl restart frr
  - echo "Router 1 setup complete"