#cloud-config
hostname: router2
fqdn: router2.local

# Configure network interfaces
write_files:
  - path: /etc/systemd/network/20-eth1.network
    content: |
      [Match]
      Name=eth1

      [Network]
      Address=10.0.2.2/24

  - path: /etc/systemd/network/30-eth2.network
    content: |
      [Match]
      Name=eth2

      [Network]
      Address=10.0.3.1/24

  - path: /etc/frr/frr.conf
    content: |
      hostname router2
      log file /var/log/frr/frr.log
      !
      router ospf
       network 10.0.0.0/8 area 0
      !
      line vty
      !

runcmd:
  - systemctl restart systemd-networkd
  - systemctl restart frr
  - echo "Router 2 setup complete"
